# See https://docs.earthly.dev/ci-integration/vendor-specific-guides/gh-actions-integration
# for details.

name: Build nightly docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.16/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

      - name: Earthly version
        run: earthly --version

      - name: Log into GitHub Container Registry
        env:
          GH_CR_PAT: ${{ secrets.GH_CR_PAT }}
        run: echo "${{ secrets.GH_CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        if: env.GH_CR_PAT != null

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: actions/checkout@v3
      - name: Checkout and build
        if: env.GH_CR_PAT != null
        env:
          GH_CR_PAT: ${{ secrets.GH_CR_PAT }}
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
          cd build/release && ./docker-nightly-earthly.sh
